
dist: focal
language: ruby

addons:
  apt:
    packages:
      - clang-12

install:
  - sudo apt-get update
  - sudo apt-get install llvm-12

script:
  - mkdir build && cd build && cmake ..
  - make
  - cd ../test && ./compile && ./run
