matrix:
  include:
    - os: osx
      osx_image: xcode12.5.1

addons:
  homebrew:
    packages:
    - cmake
    - gcc@11
    - llvm@12
    - ninja
    update: true

script:
  - mkdir build && cd build && cmake ..
  - make
  - cd ../test && ./compile && ./run
