
dist: focal
language: cpp
compiler: gcc

install:
  - sudo apt-get update
  - sudo apt-get install llvm-7

script:
  - mkdir build && cd build && cmake ..
  - make
  - cd ../test && ./compile && ./run
