
dist: focal
language: cpp
compiler: gcc

install:
  - sudo apt-get update
  - sudo apt-get install llvm-12
  - sudo apt-get install llvm-12-dev

script:
  - mkdir build && cd build && cmake ..
  - make
