
dist: focal
language: ruby

install:
  - sudo apt-get update
  - sudo apt-get install llvm-12
  - sudo apt-get install clang-12

script:
  - export CC=clang-12
  - export CXX=clang++-12
  - mkdir build && cd build && cmake ..
  - make
  - cd ../test && ./compile && ./run
