dist: focal
language: cpp
compiler: gcc

install:
  - sudo apt-get update
  - sudo apt-get install llvm-12
  - sudo apt-get install llvm-12-dev

script:
  - export LDFLAGS="-L/usr/lib/llvm-12/lib"
  - export CFLAGS="-I/usr/include/llvm-12"
  - export LD_LIBRARY_PATH=/usr/lib/llvm-12/lib:$LD_LIBRARY_PATH
  - export C_INCLUDE_PATH=/usr/include/llvm-12:/usr/include/llvm-12/llvm:$C_INCLUDE_PATH
  - export CPLUS_INCLUDE_PATH=/usr/include/llvm-12:/usr/include/llvm-12/llvm:$CPLUS_INCLUDE_PATH
  - ls -l /usr/lib/
  - ls -l /usr/lib/llvm-12/
  - ls -l /usr/
  - ls -l /usr/include/
  - sudo ls -l /usr/local/include/llvm12
  - sudo ls -l /usr/local/include/llvm12/
  - mkdir build && cd build && cmake ..
  - make
  - cd ../test && ./compile && ./run
