dist: focal
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - clang-12
      env:
        - MATRIX_EVAL="CC=clang-12 CXX=clang++-12"

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - sudo apt-get update
  - sudo apt-get install llvm-12
  - sudo apt-get install llvm-12-dev

script:
  - mkdir build && cd build && cmake ..
  - make
  - cd ../test && ./compile && ./run
