
dist: focal
language: cpp
compiler: gcc

install:
  - sudo apt-get update
  - sudo apt-get install llvm-12

script:
  - export LDFLAGS="-L/usr/local/lib/llvm-12/lib"
  - export CFLAGS="-I/usr/local/include/llvm-12"
  - export LD_LIBRARY_PATH=/usr/local/lib/llvm-12/lib:$LD_LIBRARY_PATH
  - export C_INCLUDE_PATH=/usr/local/include/llvm-12:$C_INCLUDE_PATH
  - export CPLUS_INCLUDE_PATH=/usr/local/include/llvm-12:$CPLUS_INCLUDE_PATH
  - ls /usr/local/lib/llvm-12/lib/
  - ls /usr/local/include/llvm-12/
  - ls /usr/local/
  - ls /usr/
  - ls /usr/local/include/
  - mkdir build && cd build && cmake ..
  - make
  - cd ../test && ./compile && ./run
