
dist: focal
language: cpp
compiler: gcc

install:
  - sudo apt-get update
  - sudo apt-get install llvm-12
  - sudo apt-get install llvm-12-dev

matrix:
  include:
    - env: TOOLSET=clang TOOLSET_VER=12
      addons:
        apt:
          packages:
            - clang-12
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'

script:
  - mkdir build && cd build && cmake ..
  - make
