matrix:
  include:
    - os: osx
      osx_image: xcode12.5.1

addons:
  homebrew:
    packages:
    - cmake
    - llvm@12

script:
  - ls /usr/local/Cellar
  - ls /usr/local/Cellar/llvm@12
  - ls /usr/local/Cellar/llvm@12/*
  - ls /usr/local/Cellar/llvm@12/12.0.1_1
  - export LLVM_DIR=/usr/local/Cellar/llvm@12/12.0.1_1/lib/cmake
  - mkdir build && cd build && cmake ..
  - make
  - cd ../test && ./compile && ./run
