matrix:
  include:
    - os: osx
      osx_image: xcode12.0

addons:
  homebrew:
    packages:
      - llvm@12

script:
  - mkdir build && cd build && cmake ..
  - make
  - cd ../test && ./compile && ./run
